name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release -- -j 2
      - name: Run app (Windows)
        if: runner.os == 'Windows'
        run: .\build\Release\first-app.exe
      - name: Run app (Unix)
        if: runner.os != 'Windows'
        run: ./build/first-app
